### ISSUE TITLE
Use .f90 suffix for source files

### ISSUE THREAD

**Issue by Beliavsky** [thchang/NN_MOD#1]
The .f90 suffix indicates that the source file uses free source form, not that it is restricted to the Fortran 90 standard. All Fortran compilers recognize .f90 as free source forum. I suggest using .f90 instead of .f08 for source file suffixes.

**Comment by thchang** [comment]
Thanks @Beliavsky you are correct; I had started the other naming convention thinking this would help make clear the compiler requirements (a f03/95/90 compiler will not work for this code) and is supported by most compilers.  However, noticing that ifort still does not support the f08 extension, changing the extension is a good move.

Fixed in latest commit
